name: Loan Approval MLOps CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    name: Test and Train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Run tests
        run: |
          pytest -v

      - name: Run coverage
        run: |
          pytest -v --cov=src --cov=app --cov-report=term-missing

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t loan-approval-mlops:ci .

      - name: Verify Docker image
        run: |
          docker images loan-approval-mlops:ci
